version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
      MONGO_INITDB_DATABASE: "Meu_Docker_Mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./dados_mongo:/data/db
    restart: always
